---
- name: This is a hello-world example
  hosts: all
  vars:
    plex_mount_dir: /media/plex-mount
    plex_user_account_name: plex
    plex_ubuntu_deb_url: https://downloads.plex.tv/plex-media-server-new/1.18.0.1944-f2cae8d6b/debian/plexmediaserver_1.18.0.1944-f2cae8d6b_amd64.deb
  roles:
      - rclone
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      become: true
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - aptitude
      become: true
    - name: Install plex debian file
      apt:
        deb: "{{ plex_ubuntu_deb_url }}"
        state: present
      become: true
    - name: Create a directory if it does not exist
      file:
        path: "{{ plex_mount_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ plex_user_account_name }}"
        group: "{{ plex_user_account_name }}"
      become: true