---
- name: This is a hello-world example
  hosts: all
  vars:
    plex_ubuntu_deb_url: https://downloads.plex.tv/plex-media-server-new/1.18.0.1944-f2cae8d6b/debian/plexmediaserver_1.18.0.1944-f2cae8d6b_amd64.deb
  roles:
      - rclone
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      become: true
    - name: Install VIM
      apt:
        name: "vim"
        state: latest
      become: true
    # - name: Install rclone via commandline
    #   shell: sudo curl https://rclone.org/install.sh | sudo bash
    - name: Install plex debian file
      apt:
        deb: "{{ plex_ubuntu_deb_url }}"
        state: present
      become: true