---
#Centos specfic tasks
#Renamed from "Centos-7.yml"
- name: Ensure Plex is present via YUM
  yum:
    name: "{{ plex_centos_rpm_url }}"
    state: present
  become: true

- name: Ensure ssfs is present via YUM
  yum:
    name: "sshfs"
    state: present
  become: true