---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - vars

- name: Include OS Specific Tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - vars

- name: Update repositories cache on Ubuntu Xenial
  apt:
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present
  become: true

- name: Add Unix Admins users
  user:
    name: "{{ local_unix_user }}"
    group: users
    groups: wheel
    shell: /bin/bash
    password: "{{ local_unix_password }}"
  become: true

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Add sudoers users to wheel group
  user: name=deployer groups=wheel append=yes state=present createhome=yes
  become: true

- name: Add new user to allowed ssh list
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ local_unix_user }}'

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  become: true
  notify: Restart ssh